version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    # ports:
    #   - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - database_sql:/var/lib/postgresql/data
      - ./database_sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build: ./frontend/
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
      - db
      - redis

  backend:
    build: ./shop/
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis
    # ports:
    #   - 6379:6379

volumes:
  database_sql:

networks:
  default:
    driver: bridge
